### ISSUE TITLE
HTTP requests other than GET are not signed properly

### ISSUE THREAD

**Issue by sondregj** [DNBbank/getting-started#33]
In the Node.js examples, the functions in `asv4.js` have 'GET' hardcoded as the HTTP verb, and the hashed payload is hardcoded as an empty string. 

```javascript
...
const payloadHash = hashHex('');
const canonicalRequest = `GET\n${canonicalUri}\n${canonicalQuerystring}\n${canonicalHeaders}\n${signedHeaders}\n${payloadHash}`;
...
```

The examples for Python have the same issue.

**Comment by relekang** [comment]
This has been fixed some time ago.
